# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 463913c2969a5e8fd42f6758ee76602b75ee3b18fdc47eccc16a42c7437e4a65a71c0156b7d24c70442c38449568e42a24de6e995a6ca0a58e2a50a6ba2417e8

test:
  secret_key_base: 813055f5e28d6156c167589b08615c842f40f489aaa0538c2ea35f77855a905c5a7286fade4a65ad30e08709aebd2482fa233b00bce20d013670457861f5a001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
