# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6648bbad8196f93d645409f54a184bb9772f61d122270bdc0cdb296b8e6423762a4804abacbe93414e74f872c259ac54e832f4b5577530e9d4d64dc9e12be68

test:
  secret_key_base: 3f739cf457958f83d0feaf677a8c774a465e13e85b5263c6ed7c543e253e7d7f7fd52bb9b72bf7385d3548d8fee26558d403869d79bee164e33ceeba102545ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
