# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d81f4458cb7f20f1da3fe7d528676899015f1e0cc56396f5477fa4feb93970451c1db4e1cb24ebf3b6e21ac80fa46187b270a5955507e5bef2459dcdfb6663d2

test:
  secret_key_base: 83ab0260041f8f1d4959839c8ead21654819646d4edffbd8b2abcc9ad98c44555e4461e03d504b85f75792af3baad70a673b01c9ca4abed0111ca3bdda0cc695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
