# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d15ccce836ce4f37f2869ed0724d38ddb2b3a0d70228568ebb2860af46aeb3b0cf4744ae993f20318aeabd25938d9ebf5accc028835f9400d36162f06c9de19f

test:
  secret_key_base: 99e209ed5ca6219c2f04a75b4093f33a2704e49bfc13c35cccd0713789e97c36251c4dd717c6804a58e24dc0036441fc2b71e81e2a9dbc14a39574503bddc7a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
