# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca9a0fc5f86a13a723a27c0c903cc91a70f6b3c43d4b77350a9b7e8fc91fb5387ba2fa4adaab3646c4aadcf690092a131add0967a8fd1241695091a980b1357c

test:
  secret_key_base: 582c74b281ee287f84fec7b192d01da3f4d92623fd2573e19f1d2d2882612cebb804901dc7e7d09daee9183c0ff0f113f23d43ad55d070144dba3ad50fe6e925

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
