# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47943746c12cadcdf1f021846c9d9282493a472a08ddd2de8c1295eab9b765679e3e29e3b217be7a5268ca1d4066ffc818889064bb30a6a11ba53a4f6b1eb591

test:
  secret_key_base: a8db3accc0460636182da45c9e5dde85e13aa699e6a4320412fd0310bd227b68e66c1ff7c14a259eaa91bf38c69e49d9c318868989989c70480d584c4e7d0cac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
